### PR TITLE
#15: CSS initial overhaul

### PR DESCRIPTION
**Pull request by serban-petrescu**
Added Bulma for the pure CSS.
Used moment and numerals for formatting.
Changed overall HTML structure.
Enhanced the loading "view".

### CODE REVIEW

**Comment by serban-petrescu** [comment]
You can see it live here https://serban-petrescu.github.io/dotabap.github.io/ (you will have to allow the browser to load unsafe scripts, as the generated JSON comes over plain HTTP and the GitHub pages is over HTTPS.

**Comment by larshp** [comment]
cool, looks better than the old

few thoughts:
* might want to make the font for the project name bigger, at first it seemed a bit difficult to find
* date format, DD/MM/YYYY always confuses me, consider using YYYY/MM/DD
* focus cursor in search fields

**Comment by larshp** [comment]
great, merging, thanks 😄

**Comment by serban-petrescu** [comment]
Happy to help! Will look into the sorting / filtering using Shuffle next.

**Pull request merged**
